name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  merge_pull_request:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install yarn
        run: npm install -g yarn

      - name: Install project dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Install dependencies
        run: yarn inst

      - name: Test application
        run: yarn test

      - name: Build application
        run: yarn build

      - name: Restart server application
        run: pm2 restart eduvault
