name: Continuous Deployment - Staging

on:
  push:
    branches:
      - staging

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.KEY }}
          script: cd ~/eduvault && npm run build:production && pm2 restart eduvault
